// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    CoinsInput: typeof import('./components/CoinsInput.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Hexagram: typeof import('./components/Hexagram.vue')['default']
    IconParkOutlineChinese: typeof import('~icons/icon-park-outline/chinese')['default']
    README: typeof import('./components/README.md')['default']
    Stroke: typeof import('./components/Stroke.vue')['default']
  }
}

export { }
